export const ACTIVITY_TEMPLATES = [
  {
    id: 'gym',
    name: 'Gym',
    icon: 'Dumbbell',
    category: 'health',
    points: 25,
    durationMinutes: 60,
    tips: ['Warm up for 5-10 minutes first', 'Stay hydrated throughout', 'Track your lifts to progress', 'Stretch afterward'],
  },
  {
    id: 'running',
    name: 'Running',
    icon: 'Footprints',
    category: 'health',
    points: 20,
    durationMinutes: 30,
    tips: ['Warm up with a brisk walk', 'Pace yourself, don’t sprint early', 'Hydrate before and after', 'Stretch your calves and hips after'],
  },
  {
    id: 'martial-arts',
    name: 'Martial Arts',
    icon: 'Swords',
    category: 'lifestyle',
    points: 20,
    durationMinutes: 60,
    tips: ['Stretch first', 'Prepare your equipment the night before', 'Eat something light beforehand', 'Prioritise recovery afterwards'],
  },
  {
    id: 'football',
    name: 'Football',
    icon: 'CircleDot',
    category: 'lifestyle',
    points: 15,
    durationMinutes: 60,
    tips: ['Dynamic warm-up before kickoff', 'Hydrate at every break', 'Cool down with light stretching'],
  },
  {
    id: 'basketball',
    name: 'Basketball',
    icon: 'CircleDot',
    category: 'lifestyle',
    points: 15,
    durationMinutes: 60,
    tips: ['Warm up your ankles and knees', 'Hydrate between quarters', 'Stretch calves afterward'],
  },
  {
    id: 'work',
    name: 'Work',
    icon: 'Briefcase',
    category: 'productivity',
    points: 15,
    durationMinutes: 480,
    tips: ['Stand and move every hour', 'Keep water nearby', 'Take a short walk on breaks', 'Protect your lunch break'],
  },
  {
    id: 'study',
    name: 'Study',
    icon: 'BookOpen',
    category: 'productivity',
    points: 15,
    durationMinutes: 90,
    tips: ['Use a focus timer (e.g. 25 min on, 5 off)', 'Remove phone distractions', 'Take a real break between sessions'],
  },
  {
    id: 'university',
    name: 'University',
    icon: 'GraduationCap',
    category: 'productivity',
    points: 15,
    durationMinutes: 120,
    tips: ['Review notes within 24 hours', 'Sit somewhere you focus well', 'Pack water and a snack'],
  },
  {
    id: 'gaming',
    name: 'Gaming',
    icon: 'Gamepad2',
    category: 'lifestyle',
    points: 5,
    durationMinutes: 60,
    tips: ['Drink water before you start', 'Stretch your wrists', 'Fix your posture', 'Take a break every hour'],
  },
  {
    id: 'reading',
    name: 'Reading',
    icon: 'BookOpen',
    category: 'mindset',
    points: 10,
    durationMinutes: 30,
    tips: ['Find good light for your eyes', 'Put your phone in another room', 'Even 10 pages counts'],
  },
  {
    id: 'family-time',
    name: 'Family Time',
    icon: 'Users',
    category: 'lifestyle',
    points: 20,
    durationMinutes: 60,
    tips: ['Put your phone away', 'Be fully present', 'Small moments count more than big gestures'],
  },
  {
    id: 'walking-dog',
    name: 'Walking the Dog',
    icon: 'Dog',
    category: 'health',
    points: 10,
    durationMinutes: 30,
    tips: ['Track your distance', 'Keep a steady, easy pace', 'Bring water on hot days'],
  },
  {
    id: 'meditation',
    name: 'Meditation',
    icon: 'Flower2',
    category: 'mindset',
    points: 20,
    durationMinutes: 15,
    tips: ['Find a quiet spot', 'Even 5 minutes helps', 'Focus on your breath, not on doing it perfectly'],
  },
  {
    id: 'journaling',
    name: 'Journaling',
    icon: 'NotebookPen',
    category: 'mindset',
    points: 10,
    durationMinutes: 15,
    tips: ['Write without editing yourself', 'Note one thing you’re grateful for', 'Keep it short if you’re short on time'],
  },
  {
    id: 'appointments',
    name: 'Appointments',
    icon: 'CalendarClock',
    category: 'productivity',
    points: 10,
    durationMinutes: 60,
    tips: ['Leave a buffer before and after', 'Prep any questions in advance'],
  },
  {
    id: 'shopping',
    name: 'Shopping',
    icon: 'ShoppingCart',
    category: 'lifestyle',
    points: 5,
    durationMinutes: 45,
    tips: ['Shop with a list to save time', 'Batch errands together'],
  },
  {
    id: 'meal-prep',
    name: 'Meal Prep',
    icon: 'UtensilsCrossed',
    category: 'health',
    points: 15,
    durationMinutes: 60,
    tips: ['Prep proteins in bulk', 'Portion into containers as you go', 'Label with dates'],
  },
  {
    id: 'cleaning',
    name: 'Cleaning',
    icon: 'Sparkles',
    category: 'productivity',
    points: 10,
    durationMinutes: 30,
    tips: ['Put on music or a podcast', 'One room at a time', 'Little and often beats a big clean-up'],
  },
  {
    id: 'sleep',
    name: 'Sleep',
    icon: 'Moon',
    category: 'health',
    points: 15,
    durationMinutes: 480,
    tips: ['Dim lights an hour before bed', 'Avoid screens in bed', 'Keep a consistent bedtime'],
  },
]

export const DEFAULT_CATEGORY_TIPS = {
  health: ['Small consistent effort beats occasional intensity', 'Hydrate throughout', 'Listen to your body'],
  productivity: ['Break it into smaller steps', 'Remove one distraction before you start', 'Take a real break afterward'],
  lifestyle: ['Be fully present while you do this', 'Enjoy it — this counts toward your balance too'],
  mindset: ['There’s no wrong way to do this', 'A few minutes still counts', 'Notice how you feel afterward'],
}

export function getTemplate(id) {
  return ACTIVITY_TEMPLATES.find((t) => t.id === id)
}

export function getTipsFor(templateId, category) {
  const template = getTemplate(templateId)
  if (template?.tips?.length) return template.tips
  return DEFAULT_CATEGORY_TIPS[category] || []
}
